// vueprj/src/App.vue
<script setup>
import GpuMonitor from './components/GpuMonitor.vue';
import servers from "./servers.json";

let urls = [];
let titles = [];
for (let i = 0; i < servers.length; i++) {
  urls.push(servers[i].url);
  titles.push(servers[i].title);
}
const data_length = 100; // GPU利用率历史数据长度，用于绘制折线图（先画个饼）
const sleep_time = 500;  // 间隔多久刷新一次数据，单位毫秒
</script>

<template>
  <h3><a href="https://www.do1e.cn/posts/citelab/server-help">服务器使用说明</a></h3>
  <GpuMonitor v-for="(url, index) in urls" :key="index" :url="url" :title="titles[index]" :data_length="data_length" :sleep_time="sleep_time" />
</template>

<style scoped>
body {
  margin-left: 20px;
  margin-right: 20px;
}
</style>

// nextjs/app/page.tsx
"use client";

import Link from "next/link";
import PerServer from "./components/perServer";
import servers from "./servers.json";

export default function Home() {
  return (
    <div className="max-w-7xl mx-auto">
      <h1 className="text-center">实验室GPU使用情况</h1>
      <div className="flex justify-center gap-x-2 mb-8">
        <Link
          href="https://www.do1e.cn/posts/citelab/server-help"
          className="text-blue-500"
        >
          服务器使用说明
        </Link>
      </div>
      <div>
        {Object.entries(servers).map(([key, value]) => (
          <PerServer key={key} url={value} title={key.toUpperCase()} internal_time={1000} />
        ))}
      </div>
    </div>
  );
}
